local L = LibStub("AceLocale-3.0"):NewLocale("RotationBuilder", "ruRU")
if not L then return end

L["ROB_ACTION_MOVEDOWN_TT"] = "Переместить выбранное действие вниз на одну строку"
L["ROB_ACTION_MOVEUP_TT"] = "Переместить выбранное действие вверх на одну строку"
L["ROB_ACTION_REMOVE_TT"] = "Удалить действие из списка"
L["ROB_ADDON_NAME"] = "RotationBuilder"
L["ROB_FRAME_CLOSE_TT"] = "Закрыть окно RotationBuilder"
L["ROB_FRAME_OPTIONS_TT"] = "Показать опции"
L["ROB_FRAME_ROTATIONS_TT"] = "Показать приоритеты заклинаний"
L["ROB_LOADED"] = "RotationBuilder версии %s загружен"
L["ROB_OPTION_EXPORTBINDS"] = "Экспортировать привязки \"горячих\" клавиш"
L["ROB_OPTION_EXPORTBINDS_TT"] = "Экспортировать привязки \"горячих\" клавиш"
L["ROB_OPTION_HIDECD"] = "Спрятать кулдауны (задержки заклинаний)"
L["ROB_OPTION_HIDECD_TT"] = "Спрятать отсчёт кулдаунов (задержек заклинаний) и мигающую анимацию"
L["ROB_OPTION_ICONS"] = "Опции иконки:"
L["ROB_OPTION_ICONS_C_A"] = "Прозрачность текущего действия:"
L["ROB_OPTION_ICONS_CV"] = "1"
L["ROB_OPTION_ICONS_MAX"] = "3.5"
L["ROB_OPTION_ICONS_MIN"] = ".1"
L["ROB_OPTION_ICONS_N_A"] = "Прозрачность следующего действия:"
L["ROB_OPTION_ICONS_T_A"] = "Переключить прозрачность иконок:"
L["ROB_OPTION_ICONS_T_ATT"] = [=[Введите уровень прозрачности иконки
от |cFF00FF00.1|r до |cFF00FF00 1|r
|cFF00FF00 1|r полностью не прозрачная
|cFF00FF00 .1|r практически невидимая]=]
L["ROB_OPTION_ICONSCALE"] = "Масштаб иконки:"
L["ROB_OPTION_IMPORT"] = "Опции импорта/экспорта:"
L["ROB_OPTION_LOADDEFAULT"] = "ЗАГРУЗКА"
L["ROB_OPTION_LOADDEFAULT_TT"] = "Загрузить ротацию по умолчанию для вашего класса"
L["ROB_OPTION_LOCKICONS"] = "Заблокировать иконки"
L["ROB_OPTION_LOCKICONS_TT"] = "Заблокировать иконки для предотвращения их перемещения"
L["ROB_OPTION_MINIMAP"] = "Кнопка мини-карты:"
L["ROB_OPTION_MINIMAP_TT"] = "Скрыть/показать кнопку на мини-карте"
L["ROB_OPTION_MINIMAPO"] = "Опции мини-карты:"
L["ROB_OPTION_MINIMAPPOS"] = "Расположение вокруг мини-карты"
L["ROB_OPTION_MINIMAPRAD"] = "Радиус вне мини-карты"
L["ROB_OPTION_MMPOS_CV"] = "300"
L["ROB_OPTION_MMPOS_MAX"] = "360"
L["ROB_OPTION_MMPOS_MIN"] = "1"
L["ROB_OPTION_MMRAD_CV"] = "80"
L["ROB_OPTION_MMRAD_MAX"] = "120"
L["ROB_OPTION_MMRAD_MIN"] = "1"
L["ROB_OPTION_NAIL"] = "Расположение следующего действия:"
L["ROB_OPTION_OVERWRITE"] = "Перезаписать"
L["ROB_OPTION_OVERWRITE_TT"] = "Разрешать импортируемым ротациям перезаписывать текущие ротации"
L["ROB_OPTION_RESETUI"] = "Сбросить UI"
L["ROB_OPTION_RESETUI_EXP"] = "Сбросить все UI окошки на центральное положение"
L["ROB_OPTION_RESETUI_TT"] = "Сбросить положение всех UI окошек"
L["ROB_OPTION_UI"] = "Опции UI:"
L["ROB_OPTION_UISCALE"] = "Масштаб UI:"
L["ROB_OPTION_UISCALE_ADD"] = "+"
L["ROB_OPTION_UISCALE_MIN"] = "-"
L["ROB_OPTION_UPDATERATE"] = "Обновлений в секунду:"
L["ROB_OPTION_UPDATERATE_CV"] = "5"
L["ROB_OPTION_UPDATERATE_MAX"] = "10"
L["ROB_OPTION_UPDATERATE_MIN"] = "1"
L["ROB_PROMPT_LIST_DELETE"] = "Вы уверенны, что хотите удалить?"
L["ROB_UI_ACTION_COLUMN"] = "Действие"
L["ROB_UI_ADD_ACTION_CFAIL"] = "В названиях действий не могут использовать следующие символы [ ] , ="
L["ROB_UI_ADD_ROTATION_CFAIL"] = "В названиях ротаций не могут использовать следующие символы [ ] ,"
