local L = LibStub("AceLocale-3.0"):NewLocale("RotationBuilder", "zhCN")
if not L then return end

L["defaultRotation/druid/astral_communion"] = "星界沟通"
L["defaultRotation/druid/balance"] = "平衡 7.0.3"
L["defaultRotation/druid/bear_form"] = "熊形态"
L["defaultRotation/druid/berserk"] = "狂暴"
L["defaultRotation/druid/blessing_of_the_ancients"] = "远古祝福"
L["defaultRotation/druid/brutal_slash"] = "野蛮挥砍"
L["defaultRotation/druid/cat_form"] = "猎豹形态"
L["defaultRotation/druid/celestial_alignment"] = "超凡之盟"
L["defaultRotation/druid/feral"] = "野性 7.0.3"
L["defaultRotation/druid/force_of_nature"] = "自然之力"
L["ROB_ACTION_MOVEDOWN_TT"] = "选中动作下降一位"
L["ROB_ACTION_MOVEUP_TT"] = "选中动作上升一位"
L["ROB_ACTION_REMOVE_TT"] = "从列表中移除动作"
L["ROB_ADDON_NAME"] = "循环编组器"
L["ROB_FRAME_CLOSE_TT"] = "关闭循环器窗口"
L["ROB_FRAME_OPTIONS_TT"] = "显示选项"
L["ROB_FRAME_ROTATIONS_TT"] = "显示循环"
L["ROB_LOADED"] = "已将加载循环器v%s"
L["ROB_OPTION_EXPORTBINDS"] = "输出绑定"
L["ROB_OPTION_HIDECD"] = "隐藏冷却"
L["ROB_OPTION_ICONS"] = "图标选项"
L["ROB_OPTION_ICONSCALE"] = "图标范围"
